name: Build and Submit Android
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm install
        working-directory: ./mobile

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: Build Android
        working-directory: ./mobile
        run: eas build --platform android --profile production --local --non-interactive

      - name: Create Google Services Key
        working-directory: ./mobile
        run: echo "${{ secrets.GOOGLE_SERVICES_KEY }}" | base64 -d > google-services-key.json

      - name: Submit Android
        working-directory: ./mobile
        run: |
          AAB_FILE=$(ls *.aab | head -n 1)
          eas submit --platform android --profile production --path "$AAB_FILE" --non-interactive
